### PR TITLE
adds option to set retention policy for influx

### PR DESCRIPTION
**Pull request by michbeck100**
This PR adds the option to set a retention policy for influx, default is None. Furthermore are requirements.txt with all dependencies was added.

### CODE REVIEW

**Comment by StefaE** [comment]
Hi Michael,
Thx. for the proposal. 

I'm not sure what you are trying to achieve?
- in the current version of PVForecasts, you must have created the Influx database [manually](https://github.com/StefaE/PVForecast#influx-v1x-storage): `create database <your_influx_db_name>`
- that would also be the right place to create a retention policy: `create retention policy "oneMonth" on "<your_influx_db_name>" duration 4w replication 1 default`
- note that if you declare `default`, it will be applied to all writes automatically - see [here](https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#retention-policy-management). No need to add it to the write statement.
- a retention policy in the write only make sense if you want maintain [multiple policies](https://stackoverflow.com/questions/37729008/can-i-create-different-retention-policy-for-different-measurements-in-influxdb). But your proposal doesn't cover that as each `measurement` (eg. SolCast and Mosmix) would use the same policy mentioned in `config.ini`

I'm working on an update, which will no longer require manual creation of the database. I was not planning to add a retention policy on the automatically created database - but I can certainly be convinced to change my mind there :-)

**Comment by michbeck100** [comment]
I use multiple retention policies for different intervals: daily, weekly, monthly, yearly and forever. Default is daily but the data is only retained for 24 hours with an interval of 10 seconds. Then I use multiple continuous queries to copy the data to the different retention policies using appropriate intervals, e.g. for yearly the data is grouped by 30m, so in the end I can keep a lot more data. I couldn’t do this with a 10 second interval.

**Comment by StefaE** [comment]
Thx., Michael - got it - apparently you are storing other data in the same Influx database (because none of the PVForecast data sources updates more often than every 15min). Best practice would probably be to store data in different databases (Influx 2.x has only one retention policy per 'bucket' which is the loose equivalent to 'database' in Influx 1.x)

I'll push your changes as a non-documented feature with next update (and add a retention policy to the database creation).
Will take a week and a bit (due to the other changes)

**Comment by michbeck100** [comment]
Perfect! Thanks

**Comment by StefaE** [comment]
This has been closed with v2.10 - sorry for the additional delay

**Pull request closed without merging**
